# Generated by Django 6.0.2 on 2026-09-14 09:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_tracking_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('in_transit', 'In Transit'), ('received', 'Received'), ('inspection_pending', 'Inspection Pending'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='requested', max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='orders.order')),
            ],
            options={
                'db_table': 'orders_return',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reason', models.CharField(choices=[('wrong_item', 'Wrong Item Received'), ('wrong_variant', 'Wrong Variant/Size Received'), ('transit_damage', 'Transit Damage'), ('manufacturing_defect', 'Manufacturing Defect'), ('missing_items', 'Missing Items')], max_length=30)),
                ('reason_notes', models.TextField(blank=True)),
                ('requested_quantity', models.PositiveSmallIntegerField()),
                ('received_quantity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='orders.orderitem')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.return')),
            ],
            options={
                'db_table': 'orders_returnitem',
                'constraints': [models.CheckConstraint(condition=models.Q(('requested_quantity__gt', 0)), name='returnitem_requested_quantity_gt_0')],
            },
        ),
    ]
