# Generated by Django 6.0.2 on 2026-09-14 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_return_returnitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='returnitem',
            name='approved_quantity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='disposition',
            field=models.CharField(blank=True, choices=[('restocked_retail', 'Restocked - Retail'), ('restocked_partial', 'Restocked - Partial'), ('damaged', 'Damaged'), ('rejected', 'Rejected')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='inspected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='inspected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='inspection_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='remaining_quantity_ml',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='resolution',
            field=models.CharField(blank=True, choices=[('refund', 'Refund'), ('replacement', 'Replacement'), ('not_applicable', 'Not Applicable')], max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='returnitem',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_quantity_ml__isnull', True), ('remaining_quantity_ml__gt', 0), _connector='OR'), name='returnitem_remaining_ml_positive_or_null'),
        ),
    ]
