# Generated by Django 6.0.2 on 2026-09-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_refund_refundadjustment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='refund_method',
            field=models.CharField(blank=True, choices=[('gateway', 'Payment Gateway'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI')], max_length=20, null=True),
        ),
    ]
