# Generated by Django 6.0.2 on 2026-09-14 08:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_enforce_variant_sku_not_null'),
        ('orders', '0003_order_guest_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('transaction_type', models.CharField(choices=[('purchase_receipt', 'Purchase Receipt'), ('decant_bottle_opened', 'Decant Bottle Opened'), ('adjustment', 'Adjustment'), ('return_disposition', 'Return Disposition'), ('sale', 'Sale')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=6)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='unique_default_warehouse')],
            },
        ),
        migrations.CreateModel(
            name='PartialBottleLot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remaining_ml', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reserved_ml', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('opened_at', models.DateTimeField(help_text="When this lot's volume became available for FIFO consumption. For a bottle opened during fulfillment, this is the moment it was opened. For volume recovered from a customer return, this is the inspection/restock moment, not the original bottle's historical opening date. Immutable once set.")),
                ('is_depleted', models.BooleanField(default=False)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partial_lots', to='catalog.productvariant')),
                ('source_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partial_lots_opened', to='inventory.stocktransaction')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partial_lots', to='inventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryStock',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stock_type', models.CharField(choices=[('retail', 'Retail'), ('tester', 'Tester'), ('damaged', 'Damaged'), ('promotional', 'Promotional')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity_reserved', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reorder_level', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stocks', to='catalog.productvariant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stocks', to='inventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='DecantSource',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('decant_volume_ml', models.DecimalField(decimal_places=2, max_digits=10)),
                ('decant_variant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='decant_source', to='catalog.productvariant')),
                ('source_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decant_children', to='catalog.productvariant')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('decant_volume_ml__gt', 0)), name='decantsource_decant_volume_ml_gt_0')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stock_type', models.CharField(blank=True, choices=[('retail', 'Retail'), ('tester', 'Tester'), ('damaged', 'Damaged'), ('promotional', 'Promotional'), ('partial', 'Partial')], max_length=20, null=True)),
                ('movement_type', models.CharField(choices=[('purchase_in', 'Purchase In'), ('sale_out', 'Sale Out'), ('adjustment', 'Adjustment'), ('decant_bottle_opened_retail_out', 'Decant Bottle Opened - Retail Out'), ('decant_bottle_opened_partial_in', 'Decant Bottle Opened - Partial In'), ('decant_fulfilled_from_partial', 'Decant Fulfilled From Partial'), ('return_restocked_retail', 'Return Restocked - Retail'), ('return_restocked_partial', 'Return Restocked - Partial'), ('return_damaged', 'Return Damaged')], max_length=40)),
                ('quantity_delta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('decant_preparation', 'Decant Preparation'), ('return', 'Return'), ('damaged_goods', 'Damaged Goods'), ('stolen_goods', 'Stolen Goods'), ('stock_written_off', 'Stock Written Off'), ('stocktaking_results', 'Stocktaking Results'), ('marketing_use', 'Marketing Use')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('partial_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.partialbottlelot')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='orders.orderitem')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalog.productvariant')),
                ('transaction_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stocktransaction')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='inventory.supplier')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.warehouse')),
            ],
            options={
                'indexes': [models.Index(fields=['variant', 'warehouse', 'created_at'], name='inventory_s_variant_7c5da6_idx'), models.Index(fields=['movement_type'], name='inventory_s_movemen_018f99_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='partialbottlelot',
            index=models.Index(fields=['variant', 'warehouse', 'is_depleted', 'opened_at'], name='inventory_p_variant_858281_idx'),
        ),
        migrations.AddConstraint(
            model_name='partialbottlelot',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_ml__gte', 0)), name='partiallot_remaining_ml_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='partialbottlelot',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_ml__gte', 0)), name='partiallot_reserved_ml_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='partialbottlelot',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_ml__lte', models.F('remaining_ml'))), name='partiallot_reserved_ml_lte_remaining_ml'),
        ),
        migrations.AddConstraint(
            model_name='inventorystock',
            constraint=models.UniqueConstraint(fields=('variant', 'warehouse', 'stock_type'), name='unique_variant_warehouse_stock_type'),
        ),
        migrations.AddConstraint(
            model_name='inventorystock',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='inventorystock_quantity_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='inventorystock',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_reserved__gte', 0)), name='inventorystock_quantity_reserved_gte_0'),
        ),
    ]
