# Generated by Django 6.0.2 on 2026-09-14 08:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_enforce_variant_sku_not_null'),
        ('inventory', '0001_initial'),
        ('orders', '0003_order_guest_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('purpose', models.CharField(choices=[('direct_sale', 'Direct Sale'), ('decant_fulfillment', 'Decant Fulfillment')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Unit convention follows purpose: pcs for direct_sale, ml for decant_fulfillment.', max_digits=12)),
                ('status', models.CharField(choices=[('held', 'Held'), ('confirmed', 'Confirmed'), ('released', 'Released'), ('consumed', 'Consumed')], default='held', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_reservations', to='orders.orderitem')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_reservations', to='catalog.productvariant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_reservations', to='inventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='StockReservationAllocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('allocation_type', models.CharField(choices=[('retail_unit', 'Retail Unit'), ('partial_lot', 'Partial Lot')], max_length=20)),
                ('units', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('claimed_ml', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ml_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inventory_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservation_allocations', to='inventory.inventorystock')),
                ('partial_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservation_allocations', to='inventory.partialbottlelot')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='inventory.stockreservation')),
            ],
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['order_item', 'status'], name='inventory_s_order_i_57ff40_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockreservationallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('allocation_type', 'retail_unit'), ('inventory_stock__isnull', False), ('ml_amount__isnull', True), ('partial_lot__isnull', True), ('units__isnull', False)), models.Q(('allocation_type', 'partial_lot'), ('claimed_ml__isnull', True), ('inventory_stock__isnull', True), ('ml_amount__isnull', False), ('partial_lot__isnull', False), ('units__isnull', True)), _connector='OR'), name='allocation_fields_match_allocation_type'),
        ),
    ]
