# Generated by Django 6.0.2 on 2026-09-14 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_seed_default_warehouse'),
        ('orders', '0007_returnitem_approved_quantity_returnitem_disposition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partialbottlelot',
            name='source_return_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restocked_lots', to='orders.returnitem'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='source_return_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='orders.returnitem'),
        ),
    ]
