# Generated by Django 6.0.2 on 2026-09-26 09:04

import django.core.validators
import django.db.models.functions.comparison
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_partialbottlelot_source_return_item_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'verbose_name': 'vendor', 'verbose_name_plural': 'vendors'},
        ),
        migrations.AddField(
            model_name='supplier',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='supplier',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='supplier',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='country',
            field=models.CharField(default='IN', max_length=2),
        ),
        migrations.AddField(
            model_name='supplier',
            name='external_accounting_id',
            field=models.CharField(blank=True, help_text='Contact ID in the accounting system (Zoho Books). Set by the sync.', max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='gst_treatment',
            field=models.CharField(blank=True, choices=[('registered', 'Registered business'), ('unregistered', 'Unregistered business'), ('composition', 'Composition scheme'), ('overseas', 'Overseas')], max_length=20),
        ),
        migrations.AddField(
            model_name='supplier',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\d{2}[A-Z]{5}\\d{4}[A-Z][1-9A-Z]Z[0-9A-Z]$', 'Enter a valid 15-character GSTIN.')]),
        ),
        migrations.AddField(
            model_name='supplier',
            name='legal_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='pan',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^[A-Z]{5}\\d{4}[A-Z]$', 'Enter a valid 10-character PAN.')]),
        ),
        migrations.AddField(
            model_name='supplier',
            name='payment_terms_days',
            field=models.PositiveIntegerField(default=0, help_text='Days allowed for payment. 0 means due on receipt.'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Enter a 6-digit PIN code.')]),
        ),
        migrations.AddField(
            model_name='supplier',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='state_code',
            field=models.CharField(blank=True, max_length=2, validators=[django.core.validators.RegexValidator('^\\d{2}$', 'Enter the 2-digit GST state code.')]),
        ),
        migrations.AddField(
            model_name='supplier',
            name='vendor_code',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Concat(models.Value('VEN-'), django.db.models.functions.text.LPad(django.db.models.functions.comparison.Cast('id', models.CharField()), django.db.models.functions.comparison.Greatest(django.db.models.functions.text.Length(django.db.models.functions.comparison.Cast('id', models.CharField())), 5), models.Value('0'))), output_field=models.CharField(max_length=20), unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, verbose_name='legacy address'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(help_text='Display name used across the admin.', max_length=150),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(condition=models.Q(('gstin', ''), _negated=True), fields=('gstin',), name='unique_supplier_gstin_when_set'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.CheckConstraint(condition=models.Q(('payment_terms_days__gte', 0)), name='supplier_payment_terms_days_gte_0'),
        ),
    ]
