# Generated by Django 6.0.2 on 2026-09-26 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_supplier_vendor_master'),
        ('purchases', '0002_goods_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='source_receipt_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='purchases.goodsreceiptline'),
        ),
    ]
