# Generated by Django 6.0.2 on 2026-09-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_stockmovement_source_receipt_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase_in', 'Purchase In'), ('purchase_reversal_out', 'Purchase Reversal Out'), ('sale_out', 'Sale Out'), ('adjustment', 'Adjustment'), ('decant_bottle_opened_retail_out', 'Decant Bottle Opened - Retail Out'), ('decant_bottle_opened_partial_in', 'Decant Bottle Opened - Partial In'), ('decant_fulfilled_from_partial', 'Decant Fulfilled From Partial'), ('return_restocked_retail', 'Return Restocked - Retail'), ('return_restocked_partial', 'Return Restocked - Partial'), ('return_damaged', 'Return Damaged')], max_length=40),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('purchase_receipt', 'Purchase Receipt'), ('purchase_reversal', 'Purchase Receipt Reversal'), ('decant_bottle_opened', 'Decant Bottle Opened'), ('adjustment', 'Adjustment'), ('return_disposition', 'Return Disposition'), ('sale', 'Sale')], max_length=30),
        ),
    ]
