# Generated by Django 6.0.2 on 2026-09-26 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_grn_reversal'),
        ('purchases', '0005_booked_incoming_foundation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockreservationallocation',
            name='allocation_fields_match_allocation_type',
        ),
        migrations.AddField(
            model_name='stockreservationallocation',
            name='converted_by_receipt_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='converted_allocations', to='purchases.goodsreceiptline'),
        ),
        migrations.AddField(
            model_name='stockreservationallocation',
            name='incoming_resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockreservationallocation',
            name='incoming_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('converted', 'Converted'), ('reallocated', 'Reallocated'), ('released', 'Released')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stockreservationallocation',
            name='purchase_order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_allocations', to='purchases.purchaseorderline'),
        ),
        migrations.AddField(
            model_name='stockreservationallocation',
            name='replacement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replaced', to='inventory.stockreservationallocation'),
        ),
        migrations.AddField(
            model_name='stockreservationallocation',
            name='split_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='split_remainders', to='inventory.stockreservationallocation'),
        ),
        migrations.AlterField(
            model_name='stockreservationallocation',
            name='allocation_type',
            field=models.CharField(choices=[('retail_unit', 'Retail Unit'), ('partial_lot', 'Partial Lot'), ('incoming_po_line', 'Incoming PO Line')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='stockreservationallocation',
            index=models.Index(condition=models.Q(('allocation_type', 'incoming_po_line'), ('incoming_status', 'active')), fields=['purchase_order_line'], name='alloc_active_incoming_line_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockreservationallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('allocation_type', 'retail_unit'), ('converted_by_receipt_line__isnull', True), ('incoming_resolved_at__isnull', True), ('incoming_status__isnull', True), ('inventory_stock__isnull', False), ('ml_amount__isnull', True), ('partial_lot__isnull', True), ('purchase_order_line__isnull', True), ('replacement__isnull', True), ('split_from__isnull', True), ('units__isnull', False)), models.Q(('allocation_type', 'partial_lot'), ('claimed_ml__isnull', True), ('converted_by_receipt_line__isnull', True), ('incoming_resolved_at__isnull', True), ('incoming_status__isnull', True), ('inventory_stock__isnull', True), ('ml_amount__isnull', False), ('partial_lot__isnull', False), ('purchase_order_line__isnull', True), ('replacement__isnull', True), ('split_from__isnull', True), ('units__isnull', True)), models.Q(('allocation_type', 'incoming_po_line'), ('claimed_ml__isnull', True), ('incoming_status__isnull', False), ('inventory_stock__isnull', True), ('ml_amount__isnull', True), ('partial_lot__isnull', True), ('purchase_order_line__isnull', False), ('units__isnull', False)), _connector='OR'), name='allocation_fields_match_allocation_type'),
        ),
        migrations.AddConstraint(
            model_name='stockreservationallocation',
            constraint=models.CheckConstraint(condition=models.Q(('incoming_status__isnull', True), models.Q(('converted_by_receipt_line__isnull', True), ('incoming_resolved_at__isnull', True), ('incoming_status', 'active'), ('replacement__isnull', True)), models.Q(('converted_by_receipt_line__isnull', False), ('incoming_resolved_at__isnull', False), ('incoming_status', 'converted'), ('replacement__isnull', False)), models.Q(('converted_by_receipt_line__isnull', True), ('incoming_resolved_at__isnull', False), ('incoming_status', 'reallocated'), ('replacement__isnull', False)), models.Q(('converted_by_receipt_line__isnull', True), ('incoming_resolved_at__isnull', False), ('incoming_status', 'released'), ('replacement__isnull', True)), _connector='OR'), name='allocation_incoming_lifecycle_fields'),
        ),
        migrations.AddConstraint(
            model_name='stockreservationallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('allocation_type', 'incoming_po_line'), _negated=True), ('units__gt', 0), _connector='OR'), name='allocation_incoming_units_gt_0'),
        ),
    ]
