# Generated by Django 6.0.2 on 2026-09-26 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_incoming_allocation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockreservationallocation',
            options={'permissions': [('reallocate_incoming_allocation', 'Can reallocate incoming (booked) allocations')]},
        ),
    ]
