# Generated by Django 6.0.2 on 2026-09-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productedition_image_productvariant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='shipping_surcharge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('shipping_surcharge__gte', 0)), name='productvariant_shipping_surcharge_gte_0'),
        ),
    ]
