# Generated by Django 6.0.2 on 2026-09-14 13:07

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_enable_pg_trgm'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='catalog/variant_images/')),
                ('role', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary / Hover'), ('gallery', 'Gallery')], default='gallery', max_length=10)),
                ('alt_text', models.CharField(blank=True, help_text='Accessibility/SEO alt text. Shown to screen readers and used by image search.', max_length=255)),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Deterministic gallery order, lowest first.')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='productedition',
            name='is_indexable',
            field=models.BooleanField(default=True, help_text="Whether this edition's page should be indexable by search engines. Does not affect whether the page is reachable — only its SEO robots signal. Use this to noindex a thin/duplicate edition without deactivating it."),
        ),
        migrations.AddField(
            model_name='productedition',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Meta description for search results. No automatic fallback — left blank if unset.', max_length=300),
        ),
        migrations.AddField(
            model_name='productedition',
            name='og_description',
            field=models.CharField(blank=True, help_text='Open Graph description override. Falls back to meta_description.', max_length=300),
        ),
        migrations.AddField(
            model_name='productedition',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title override. Falls back to seo_title, then the display name.', max_length=95),
        ),
        migrations.AddField(
            model_name='productedition',
            name='seo_title',
            field=models.CharField(blank=True, help_text="Overrides the auto-generated <title>. Falls back to the edition's display name if blank.", max_length=70),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='brand_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='perfumenote',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='perfumenote_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='product_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='productedition',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='edition_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='productedition',
            constraint=models.UniqueConstraint(condition=models.Q(('slug__isnull', False)), fields=('product', 'slug'), name='unique_edition_slug_per_product'),
        ),
        migrations.AddField(
            model_name='productvariantimage',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.productvariant'),
        ),
        migrations.AddConstraint(
            model_name='productvariantimage',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'primary')), fields=('variant',), name='unique_primary_image_per_variant'),
        ),
        migrations.AddConstraint(
            model_name='productvariantimage',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'secondary')), fields=('variant',), name='unique_secondary_image_per_variant'),
        ),
    ]
