# Generated by Django 6.0.2 on 2026-09-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_productvariantimage_productedition_is_indexable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productedition',
            name='release_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productedition',
            name='concentration',
            field=models.CharField(choices=[('edc', 'Eau de Cologne'), ('edt', 'Eau de Toilette'), ('edp', 'Eau de Parfum'), ('extrait', 'Extrait de Parfum'), ('attar', 'Attar')], db_index=True, default='edp', max_length=20),
        ),
    ]
