# Generated by Django 6.0.2 on 2026-09-26 09:27

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.comparison
import django.db.models.functions.text
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0008_productedition_release_year_attar'),
        ('inventory', '0005_supplier_vendor_master'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('po_number', models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Concat(models.Value('PO-'), django.db.models.functions.text.LPad(django.db.models.functions.comparison.Cast('id', models.CharField()), django.db.models.functions.comparison.Greatest(django.db.models.functions.text.Length(django.db.models.functions.comparison.Cast('id', models.CharField())), 5), models.Value('0'))), output_field=models.CharField(max_length=20), unique=True)),
                ('order_date', models.DateField(default=django.utils.timezone.localdate)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('vendor_reference', models.CharField(blank=True, help_text="The vendor's quote or order number.", max_length=100)),
                ('amounts_include_tax', models.BooleanField(default=False, help_text="Tick if the vendor's prices include GST.")),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('partially_received', 'Partially received'), ('received', 'Received'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('close_reason', models.TextField(blank=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.supplier', verbose_name='vendor')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-id'],
                'permissions': [('issue_purchaseorder', 'Can issue purchase order'), ('cancel_purchaseorder', 'Can cancel purchase order')],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity_ordered', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Vendor price per unit before the line discount.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('line_discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount for the whole line, not per unit.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, help_text='GST % snapshot. Required before issue when prices include tax.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('hsn_code', models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator('^\\d{4,8}$', 'Enter a 4 to 8 digit HSN code.')])),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.purchaseorder')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_lines', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity_ordered__gt', 0)), name='po_line_quantity_ordered_gt_0'), models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='po_line_unit_price_gte_0'), models.CheckConstraint(condition=models.Q(('line_discount_amount__gte', 0)), name='po_line_discount_gte_0'), models.CheckConstraint(condition=models.Q(('line_discount_amount__lte', django.db.models.expressions.CombinedExpression(models.F('unit_price'), '*', models.F('quantity_ordered')))), name='po_line_discount_lte_gross'), models.CheckConstraint(condition=models.Q(('tax_rate__isnull', True), models.Q(('tax_rate__gte', 0), ('tax_rate__lte', 100)), _connector='OR'), name='po_line_tax_rate_0_to_100')],
            },
        ),
    ]
