# Generated by Django 6.0.2 on 2026-09-26 09:43

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.comparison
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_productedition_release_year_attar'),
        ('inventory', '0005_supplier_vendor_master'),
        ('purchases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('grn_number', models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Concat(models.Value('GRN-'), django.db.models.functions.text.LPad(django.db.models.functions.comparison.Cast('id', models.CharField()), django.db.models.functions.comparison.Greatest(django.db.models.functions.text.Length(django.db.models.functions.comparison.Cast('id', models.CharField())), 5), models.Value('0'))), output_field=models.CharField(max_length=20), unique=True)),
                ('receipt_type', models.CharField(choices=[('standard', 'Standard'), ('opening', 'Opening stock'), ('reversal', 'Reversal')], default='standard', max_length=20)),
                ('received_date', models.DateField(default=django.utils.timezone.localdate)),
                ('vendor_document_reference', models.CharField(blank=True, help_text='Delivery challan or invoice number printed on the delivery. Not a bill.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='purchases.purchaseorder')),
                ('reverses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='purchases.goodsreceipt')),
                ('stock_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt', to='inventory.stocktransaction')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='inventory.supplier', verbose_name='vendor')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-id'],
                'permissions': [('post_goodsreceipt', 'Can post goods receipt'), ('cancel_goodsreceipt', 'Can cancel goods receipt')],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stock_type', models.CharField(choices=[('retail', 'Retail'), ('damaged', 'Damaged')], default='retail', max_length=20)),
                ('quantity', models.PositiveIntegerField(help_text='Units physically received.', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_cost', models.DecimalField(decimal_places=4, help_text='Cost per unit excluding tax. Frozen when the receipt is posted.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('po_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='purchases.purchaseorderline', verbose_name='PO line')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.goodsreceipt')),
                ('reverses_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_lines', to='purchases.goodsreceiptline')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_lines', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='goodsreceipt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('receipt_type', 'standard'), _negated=True), models.Q(('purchase_order__isnull', False), ('supplier__isnull', False)), _connector='OR'), name='grn_standard_has_po_and_supplier'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceipt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('receipt_type', 'opening'), _negated=True), ('purchase_order__isnull', True), _connector='OR'), name='grn_opening_has_no_po'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceipt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('receipt_type', 'reversal'), _negated=True), ('reverses__isnull', False), _connector='OR'), name='grn_reversal_has_original'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceipt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'posted'), _negated=True), models.Q(('posted_at__isnull', False), ('stock_transaction__isnull', False)), _connector='OR'), name='grn_posted_has_transaction'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='grn_line_quantity_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='grn_line_unit_cost_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptline',
            constraint=models.CheckConstraint(condition=models.Q(('tax_rate__isnull', True), models.Q(('tax_rate__gte', 0), ('tax_rate__lte', 100)), _connector='OR'), name='grn_line_tax_rate_0_to_100'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptline',
            constraint=models.CheckConstraint(condition=models.Q(('stock_type__in', ['retail', 'damaged'])), name='grn_line_stock_type_retail_or_damaged'),
        ),
    ]
