# Generated by Django 6.0.2 on 2026-09-26 10:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_productedition_release_year_attar'),
        ('purchases', '0002_goods_receipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-id'], 'permissions': [('issue_purchaseorder', 'Can issue purchase order'), ('cancel_purchaseorder', 'Can cancel purchase order'), ('close_purchaseorder', 'Can close purchase order')]},
        ),
        migrations.CreateModel(
            name='ReceiptDiscrepancy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('observed_item_description', models.CharField(blank=True, help_text='For a wrong item not in the catalogue: describe what arrived.', max_length=255)),
                ('discrepancy_type', models.CharField(choices=[('short', 'Short'), ('damaged', 'Damaged'), ('wrong_item', 'Wrong item'), ('excess', 'Excess')], max_length=20)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('resolution', models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('replacement_expected', 'Replacement expected'), ('vendor_credit_expected', 'Vendor credit expected'), ('written_off', 'Written off'), ('return_planned', 'Return planned')], max_length=30)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('po_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discrepancies', to='purchases.purchaseorderline', verbose_name='PO line')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancies', to='purchases.goodsreceipt')),
                ('receipt_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discrepancies', to='purchases.goodsreceiptline')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(blank=True, help_text='For a wrong item: what actually arrived, if it is in the catalogue.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_discrepancies', to='catalog.productvariant')),
            ],
            options={
                'verbose_name': 'receipt discrepancy',
                'verbose_name_plural': 'receipt discrepancies',
                'ordering': ['-id'],
                'permissions': [('resolve_receiptdiscrepancy', 'Can resolve receipt discrepancy')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='discrepancy_quantity_gt_0'), models.CheckConstraint(condition=models.Q(models.Q(('discrepancy_type', 'damaged'), _negated=True), ('receipt_line__isnull', False), _connector='OR'), name='discrepancy_damaged_has_receipt_line'), models.CheckConstraint(condition=models.Q(models.Q(('discrepancy_type__in', ['short', 'excess']), _negated=True), ('po_line__isnull', False), _connector='OR'), name='discrepancy_short_excess_has_po_line'), models.CheckConstraint(condition=models.Q(models.Q(('discrepancy_type', 'wrong_item'), _negated=True), ('variant__isnull', False), models.Q(('observed_item_description', ''), _negated=True), _connector='OR'), name='discrepancy_wrong_item_described'), models.CheckConstraint(condition=models.Q(models.Q(('resolution', ''), ('resolved_at__isnull', True), ('status', 'open')), models.Q(('resolved_at__isnull', False), ('status', 'resolved'), models.Q(('resolution', ''), _negated=True)), _connector='OR'), name='discrepancy_resolution_matches_status'), models.UniqueConstraint(condition=models.Q(('receipt_line__isnull', False)), fields=('receipt_line', 'discrepancy_type'), name='unique_discrepancy_per_receipt_line_type')],
            },
        ),
    ]
