# Generated by Django 6.0.2 on 2026-09-26 11:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_grn_reversal'),
        ('purchases', '0003_receipt_discrepancy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsreceipt',
            options={'ordering': ['-id'], 'permissions': [('post_goodsreceipt', 'Can post goods receipt'), ('cancel_goodsreceipt', 'Can cancel goods receipt'), ('reverse_goodsreceipt', 'Can reverse goods receipt')]},
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='reversal_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='goodsreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('receipt_type', 'reversal'), ('reverses__isnull', True), _connector='OR'), name='grn_reverses_only_on_reversal'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceipt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('receipt_type', 'reversal'), ('status', 'posted'), _negated=True), models.Q(('reversal_reason', ''), _negated=True), _connector='OR'), name='grn_reversal_has_reason'),
        ),
    ]
