# Generated by Django 6.0.2 on 2026-09-26 17:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_productedition_release_year_attar'),
        ('purchases', '0004_grn_reversal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedQuantityChange',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('old_quantity', models.PositiveIntegerField()),
                ('new_quantity', models.PositiveIntegerField()),
                ('note', models.TextField(help_text='Vendor confirmation or reason for the change.')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='purchaseorderline',
            options={'ordering': ['id'], 'permissions': [('confirm_booked_quantity', 'Can confirm booked quantity')]},
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='confirmed_booked_quantity',
            field=models.PositiveIntegerField(default=0, help_text="Total units the vendor has confirmed for this line, including units already received. Not the remaining quantity: ordered 10, received 4, vendor confirms the other 6 -> enter 10. Changed only through 'Confirm booked quantity'.", verbose_name='Vendor-confirmed total (cumulative)'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('confirmed_booked_quantity__gte', 0)), name='po_line_confirmed_booked_gte_0'),
        ),
        migrations.AddField(
            model_name='bookedquantitychange',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookedquantitychange',
            name='purchase_order_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booked_quantity_changes', to='purchases.purchaseorderline'),
        ),
    ]
